using PosApi.Models.Enums;

namespace PosApi.DTOs.Customer;

public class CreateCustomerDto
{
    /// <summary>
    /// Optional - auto-generated by the service (e.g. "CUS00001") when not supplied.
    /// </summary>
    public string? CustomerCode { get; set; }
    public string CustomerName { get; set; } = string.Empty;
    public string? Mobile { get; set; }
    public string? Address { get; set; }
    public string? Email { get; set; }
    public CustomerType CustomerType { get; set; } = CustomerType.Regular;
    public decimal CreditLimit { get; set; }
}

public class CustomerDto
{
    public string CustomerCode { get; set; } = string.Empty;
    public string CustomerName { get; set; } = string.Empty;
    public string? Mobile { get; set; }
    public string? Address { get; set; }
    public string? Email { get; set; }
    public CustomerType CustomerType { get; set; }
    public int LoyaltyPoints { get; set; }
    public decimal CreditLimit { get; set; }
    public bool IsActive { get; set; }
    public DateTime? CreatedAt { get; set; }
}
