namespace PosApi.DTOs.Security;

public class CreateSystemUserDto
{
    /// <summary>
    /// Optional - auto-generated by the service (e.g. "USR00001") when not supplied.
    /// </summary>
    public string? UserCode { get; set; }
    public string Username { get; set; } = string.Empty;
    public string Password { get; set; } = string.Empty;
    public string? FullName { get; set; }
    public string? Email { get; set; }
    public string? Mobile { get; set; }
    public string? BranchCode { get; set; }
    public int? RoleId { get; set; }
    public bool IsActive { get; set; } = true;
}

/// <summary>
/// Updates profile fields for an existing system user. Password changes are handled separately
/// (e.g. via a dedicated auth/reset-password flow) and are intentionally not exposed here.
/// </summary>
public class UpdateSystemUserDto
{
    public string? FullName { get; set; }
    public string? Email { get; set; }
    public string? Mobile { get; set; }
    public string? BranchCode { get; set; }
    public int? RoleId { get; set; }
    public bool IsActive { get; set; }
}

public class SystemUserDto
{
    public string UserCode { get; set; } = string.Empty;
    public string Username { get; set; } = string.Empty;
    public string? FullName { get; set; }
    public string? Email { get; set; }
    public string? Mobile { get; set; }
    public string? BranchCode { get; set; }
    public int? RoleId { get; set; }
    public string? RoleName { get; set; }
    public bool IsActive { get; set; }
    public DateTime? LastLogin { get; set; }
    public DateTime? CreatedAt { get; set; }
    public DateTime? UpdatedAt { get; set; }
}
